# Generated by Django 3.0.5 on 2020-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
