# Generated by Django 3.0.5 on 2020-05-19 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_chart_point"),
    ]

    operations = [
        migrations.RemoveField(model_name="incomeoutcome", name="time",),
        migrations.AddField(
            model_name="incomeoutcome",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
